// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgmlNW4LMdp-CzoWf87Wz67CBRiYEj0sM',
    appId: '1:196358992254:web:85c9f97534f4418bf8832f',
    messagingSenderId: '196358992254',
    projectId: 'iot-ktech-console',
    authDomain: 'iot-ktech-console.firebaseapp.com',
    storageBucket: 'iot-ktech-console.appspot.com',
    measurementId: 'G-HWXQLMJYDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3-tkzqCizCE489ktwF25lJZ2DGabmXwM',
    appId: '1:196358992254:android:5e22639ec3b99f06f8832f',
    messagingSenderId: '196358992254',
    projectId: 'iot-ktech-console',
    storageBucket: 'iot-ktech-console.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb5887SvmqmHy00QR6iFe9oMold7lBM4Q',
    appId: '1:196358992254:ios:fef1615867dc1b4af8832f',
    messagingSenderId: '196358992254',
    projectId: 'iot-ktech-console',
    storageBucket: 'iot-ktech-console.appspot.com',
    iosBundleId: 'com.example.iotMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb5887SvmqmHy00QR6iFe9oMold7lBM4Q',
    appId: '1:196358992254:ios:a9dab47b6f96bb96f8832f',
    messagingSenderId: '196358992254',
    projectId: 'iot-ktech-console',
    storageBucket: 'iot-ktech-console.appspot.com',
    iosBundleId: 'com.example.iotMobileApp.RunnerTests',
  );
}
